### ISSUE TITLE
readNdefData() is returned "UnDefine"

### ISSUE THREAD

**Issue by nazuna1** [techniq/node-pn532#17]
hi, 
readNdefData() is returned "UnDefine"

My Test Case is Android NFC and few NFC/RFID Tags

and Test Code is below that examples/read_data.js
`
var rfid = new pn532.PN532(serialPort);
rfid.on(
 ......
rfid.readNdefData().then(function(data) {
....
});
....
`
node_pn532 read only one card in test case

**Comment by techniq** [comment]
@nazuna1 try to enable [debug logging](https://github.com/techniq/node-pn532#debug-logging) to get more details.

Also, which hardware are you using?  See this [discussion](https://github.com/techniq/node-pn532/issues/6) regarding setup and potential issues.  I've always used [this](https://www.adafruit.com/product/364) board as well as a custom board built with the PN532 chip, but I know that user struggled using the [Arduino shield](https://www.adafruit.com/product/789) and ended up [purchasing](https://github.com/techniq/node-pn532/issues/6#issuecomment-161064771) the same board I was using and it worked for him.

I currently do not  have a setup in place to provide much more help right now to be honest.  I haven't actively developed on the library for 2 years now (but still have it being used in production).
