### ISSUE TITLE
pn532 in UART mode doesn't start properly on Raspberry PI

### ISSUE THREAD

**Issue by viking** [techniq/node-pn532#3]
I believe this is same problem as detailed here: https://answers.launchpad.net/nfcpy/+question/237349

**Comment by techniq** [comment]
I added some more delay in the wakeup that resolved an issue I was using on my Macbook using an FTDI cable.  Maybe try again and let me know your findings (I haven't pushed an updated to NPM yet, so you'll need to pull from source until I do so).

**Comment by techniq** [comment]
I've tagged v0.0.5 if you want to give it a try

**Comment by viking** [comment]
Unfortunately I don't have the hardware at the moment to try it, but when I do again I will.
